{{- if $.Values.providerIntegration.resourcesApi.controlPlaneResourceEnabled }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    {{- if $.Values.global.metadata.annotations }}
    {{- range $key, $val := $.Values.global.metadata.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "cluster.labels.common" $ | nindent 4 }}
    {{- include "cluster.labels.custom" $ | indent 4 }}
  name: {{ include "cluster.resource.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  machineTemplate:
    metadata:
      labels:
        {{- include "cluster.labels.common" $ | nindent 8 }}
        {{- include "cluster.labels.custom" $ | indent 8 }}
    infrastructureRef:
      apiVersion: {{ $.Values.providerIntegration.controlPlane.resources.infrastructureMachineTemplate.group }}/{{ $.Values.providerIntegration.controlPlane.resources.infrastructureMachineTemplate.version }}
      kind: {{ $.Values.providerIntegration.controlPlane.resources.infrastructureMachineTemplate.kind }}
      name: {{ include "cluster.resource.name" $ }}-control-plane-{{ include "cluster.data.hash" (dict "data" (include $.Values.providerIntegration.controlPlane.resources.infrastructureMachineTemplateSpecTemplateName $) "salt" $.Values.providerIntegration.hashSalt) }}
  kubeadmConfigSpec:
    format: ignition
    ignition:
      {{- include "cluster.internal.controlPlane.kubeadm.ignition" $ | indent 6 }}
    clusterConfiguration:
      # Avoid accessibility issues (e.g. on private clusters) and potential future rate limits for
      # the default `registry.k8s.io`.
      imageRepository: docker.io/giantswarm
      # API server configuration
      apiServer:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.apiServer" $ | indent 8 }}
      controllerManager:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.controllerManager" $ | indent 8 }}
      scheduler:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.scheduler" $ | indent 8 }}
      etcd:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.etcd" $ | indent 8 }}
      networking:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.networking" $ | indent 8 }}
    initConfiguration:
      {{- include "cluster.internal.controlPlane.kubeadm.initConfiguration" $ | indent 6 }}
    joinConfiguration:
      {{- include "cluster.internal.controlPlane.kubeadm.joinConfiguration" $ | indent 6 }}
    files:
    {{- include "cluster.internal.controlPlane.kubeadm.files" $ | indent 4 }}
    preKubeadmCommands:
    {{- include "cluster.internal.controlPlane.kubeadm.preKubeadmCommands" $ | indent 4 }}
    postKubeadmCommands:
    {{- include "cluster.internal.controlPlane.kubeadm.postKubeadmCommands" $ | indent 4 }}
    users:
    {{- include "cluster.internal.kubeadm.users" $ | indent 4 }}
  replicas: {{ .Values.global.controlPlane.replicas }}
  version: v{{ trimPrefix "v" .Values.providerIntegration.kubernetesVersion }}
{{- end }}
