{{- if $.Values.providerIntegration.resourcesApi.controlPlaneResourceEnabled }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    {{- include "cluster.annotations.custom" $ | indent 4 }}
  labels:
    {{- include "cluster.labels.common" $ | nindent 4 }}
    {{- include "cluster.labels.custom" $ | indent 4 }}
  name: {{ include "cluster.resource.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  machineTemplate:
    metadata:
      labels:
        {{- include "cluster.labels.common" $ | nindent 8 }}
        {{- include "cluster.labels.custom" $ | indent 8 }}
    infrastructureRef:
      apiVersion: {{ $.Values.providerIntegration.controlPlane.resources.infrastructureMachineTemplate.group }}/{{ $.Values.providerIntegration.controlPlane.resources.infrastructureMachineTemplate.version }}
      kind: {{ $.Values.providerIntegration.controlPlane.resources.infrastructureMachineTemplate.kind }}
      {{- $_ := set $ "osImage" $.Values.providerIntegration.osImage }}
      {{- $_ = set $ "kubernetesVersion" $.Values.providerIntegration.kubernetesVersion }}
      name: {{ include "cluster.resource.name" $ }}-control-plane-{{ include "cluster.data.hash" (dict "data" (include $.Values.providerIntegration.controlPlane.resources.infrastructureMachineTemplateSpecTemplateName $) "salt" $.Values.providerIntegration.hashSalt) }}
  kubeadmConfigSpec:
    diskSetup:
      # Workaround for https://github.com/kubernetes-sigs/cluster-api/issues/7679.
      # Don't define partitions here, they are defined in "ignition.containerLinuxConfig.additionalConfig"
      {{- include "cluster.internal.controlPlane.kubeadm.diskSetup" $ | indent 6 }}
    mounts:
    {{- include "cluster.internal.controlPlane.kubeadm.mounts" $ | indent 2 }}
    format: ignition
    ignition:
      {{- include "cluster.internal.controlPlane.kubeadm.ignition" $ | indent 6 }}
    clusterConfiguration:
      # Avoid accessibility issues (e.g. on private clusters) and potential future rate limits for
      # the default `registry.k8s.io`.
      imageRepository: {{ include "cluster.image.registry" $ }}/giantswarm
      # API server configuration
      apiServer:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.apiServer" $ | indent 8 }}
      controllerManager:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.controllerManager" $ | indent 8 }}
      scheduler:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.scheduler" $ | indent 8 }}
      etcd:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.etcd" $ | indent 8 }}
      networking:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.networking" $ | indent 8 }}
    initConfiguration:
      {{- include "cluster.internal.controlPlane.kubeadm.initConfiguration" $ | indent 6 }}
    joinConfiguration:
      {{- include "cluster.internal.controlPlane.kubeadm.joinConfiguration" $ | indent 6 }}
    files:
    {{- include "cluster.internal.controlPlane.kubeadm.files" $ | indent 4 }}
    preKubeadmCommands:
    {{- include "cluster.internal.controlPlane.kubeadm.preKubeadmCommands" $ | indent 4 }}
    {{- $postKubeadmCommands := include "cluster.internal.controlPlane.kubeadm.postKubeadmCommands" $ }}
    {{- if $postKubeadmCommands }}
    postKubeadmCommands:
    {{- $postKubeadmCommands | indent 4 }}
    {{- end }}
    {{- $users := include "cluster.internal.kubeadm.users" $ }}
    {{- if $users }}
    users:
    {{- $users | indent 4 }}
    {{- end }}
  replicas: {{ .Values.global.controlPlane.replicas }}
  rolloutBefore:
    {{- toYaml $.Values.internal.advancedConfiguration.controlPlane.rolloutBefore | nindent 4 }}
  version: v{{ include "cluster.component.kubernetes.version" $ }}
{{- end }}
