apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    {{- if $.Values.global.metadata.annotations }}
    {{- range $key, $val := $.Values.global.metadata.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "cluster.labels.common" $ | nindent 4 }}
    {{- if $.Values.global.metadata.labels }}
    {{- range $key, $val := $.Values.global.metadata.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "cluster.resource.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  version: v{{ trimPrefix "v" .Values.internal.kubernetesVersion }}
  kubeadmConfigSpec:
    format: ignition
    ignition:
      {{- include "cluster.internal.controlPlane.kubeadm.ignition" $ | indent 6 }}
    clusterConfiguration:
      # Avoid accessibility issues (e.g. on private clusters) and potential future rate limits for
      # the default `registry.k8s.io`.
      imageRepository: docker.io/giantswarm
      # API server configuration
      apiServer:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.apiServer" $ | indent 8 }}
      controllerManager:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.controllerManager" $ | indent 8 }}
      scheduler:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.scheduler" $ | indent 8 }}
      etcd:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.etcd" $ | indent 8 }}
      networking:
        {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.networking" $ | indent 8 }}
    initConfiguration:
      {{- include "cluster.internal.controlPlane.kubeadm.initConfiguration" $ | indent 6 }}
    joinConfiguration:
      {{- include "cluster.internal.controlPlane.kubeadm.joinConfiguration" $ | indent 6 }}
    files:
    {{- include "cluster.internal.controlPlane.kubeadm.files" . | indent 4 }}
    preKubeadmCommands:
    {{- include "cluster.internal.controlPlane.kubeadm.preKubeadmCommands" $ | indent 4 }}
    postKubeadmCommands:
    {{- include "cluster.internal.controlPlane.kubeadm.postKubeadmCommands" $ | indent 4 }}
    users:
    {{- include "cluster.internal.kubeadm.users" $ | indent 4 }}
