apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    {{- if .Values.metadata.annotations }}
    {{- range $key, $val := .Values.metadata.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- if .Values.metadata.labels }}
    {{- range $key, $val := .Values.metadata.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  version: v{{ trimPrefix "v" .Values.internal.kubernetesVersion }}
  kubeadmConfigSpec:
    format: ignition
    ignition:
      containerLinuxConfig:
        additionalConfig: |
          systemd:
            units:
            {{- include "cluster.kubeadmControlPlane.kubeadmConfigSpec.ignition.containerLinuxConfig.additionalConfig.systemd.units" $ | indent 12 }}
          storage:
            filesystems:
            {{- include "cluster.kubeadmControlPlane.kubeadmConfigSpec.ignition.containerLinuxConfig.additionalConfig.storage.filesystems" $ | indent 12 }}
            directories:
            {{- include "cluster.kubeadmControlPlane.kubeadmConfigSpec.ignition.containerLinuxConfig.additionalConfig.storage.directories" $ | indent 12 }}
    clusterConfiguration:
      # Avoid accessibility issues (e.g. on private clusters) and potential future rate limits for
      # the default `registry.k8s.io`.
      imageRepository: docker.io/giantswarm

      # API server configuration
      apiServer:
        # Timeout for the API server to appear.
        # TODO: this should be aligned with alerts, i.e. time here should be less than the time after which we alert for API server replica being down.
        timeoutForControlPlane: 20min
        certSANs:
        - localhost
        - 127.0.0.1
        - "api.{{ include "resource.default.name" $ }}.{{ required "The baseDomain value is required" .Values.connectivity.baseDomain }}"
        - "apiserver.{{ include "resource.default.name" $ }}.{{ required "The baseDomain value is required" .Values.connectivity.baseDomain }}"
        extraArgs:
          {{- include "cluster.internal.controlPlane.kubeadm.clusterConfiguration.apiServer" $ | indent 10 }}
