{{- if $.Values.providerIntegration.resourcesApi.controlPlaneResourceEnabled }}
{{- if $.Values.providerIntegration.resourcesApi.machineHealthCheckResourceEnabled }}
{{- if $.Values.global.controlPlane.machineHealthCheck.enabled }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  {{- $annotations := include "cluster.annotations.custom" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "cluster.labels.common" $ | nindent 4 }}
    {{- if $.Values.global.metadata.labels }}
    {{- range $key, $val := $.Values.global.metadata.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "cluster.resource.name" . }}-control-plane
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ include "cluster.resource.name" $ }}
  maxUnhealthy: {{ $.Values.global.controlPlane.machineHealthCheck.maxUnhealthy }}
  nodeStartupTimeout: {{ $.Values.global.controlPlane.machineHealthCheck.nodeStartupTimeout }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.resource.name" $ }}
      cluster.x-k8s.io/control-plane: ""
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: {{ $.Values.global.controlPlane.machineHealthCheck.unhealthyUnknownTimeout }}
  - type: Ready
    status: "False"
    timeout: {{ $.Values.global.controlPlane.machineHealthCheck.unhealthyNotReadyTimeout }}
{{- end }}
{{- end }}
{{- end }}
