{{- if $.Values.providerIntegration.resourcesApi.machinePoolResourcesEnabled }}
{{- if eq $.Values.providerIntegration.resourcesApi.nodePoolKind "MachineDeployment" }}
{{- range $nodePoolName, $nodePoolConfig := $.Values.global.nodePools | default $.Values.providerIntegration.workers.defaultNodePools }}
{{- $_ := set $ "nodePool" (dict "name" $nodePoolName "config" $nodePoolConfig) }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  labels:
    giantswarm.io/machine-deployment: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
    {{- include "cluster.labels.common" $ | nindent 4 }}
  name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}-{{ include "cluster.internal.workers.kubeadmConfig.spec.hash" $ }}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec: {{-- include "cluster.internal.workers.kubeadmConfig.spec.hash" $ | nindent 6 }}
---
{{- end }}
{{- end }}
{{- end }}
