{{/*
CAPA reconciliation does not roll AWSMachinePool nodes if the referenced `KubeadmConfig` changes
(such as `KubeadmConfig.spec.{files,preKubeadmCommands,...}`).
We append a hash of `KubeadmConfig.spec` to the `KubeadmConfig` name since that enforces a new bootstrap
secret name, triggering a rollout of nodes in CAPA's `AWSMachinePool` reconciler.
See https://github.com/giantswarm/roadmap/issues/2217 and
https://github.com/kubernetes-sigs/cluster-api/issues/8858 – detecting a changed data secret name
became a feature and we need to keep the hashing in place.

Full-line comments are excluded from the hash so that simple changes will not lead to
node rollouts and thus possibly interruped workloads for customers.
*/}}
{{- if $.Values.providerIntegration.resourcesApi.machinePoolResourcesEnabled }}
{{- if eq $.Values.providerIntegration.resourcesApi.nodePoolKind "MachinePool" }}
{{- if $.Values.providerIntegration.workers.kubeadmConfig.enabled }}
{{- range $nodePoolName, $nodePoolConfig := $.Values.global.nodePools | default $.Values.providerIntegration.workers.defaultNodePools }}
{{- $_ := set $ "nodePool" (dict "name" $nodePoolName "config" $nodePoolConfig) }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfig
metadata:
  annotations:
    machine-pool.giantswarm.io/name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
    {{- include "cluster.annotations.custom" $ | indent 4 }}
    {{- if $nodePoolConfig.annotations }}
    {{- range $key, $val := $nodePoolConfig.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "cluster.labels.common.all" $ | nindent 4 }}
    giantswarm.io/machine-pool: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
    {{- if $nodePoolConfig.labels }}
    {{- range $key, $val := $nodePoolConfig.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}-{{ include "cluster.internal.workers.kubeadmConfig.spec.hash" $ }}
  namespace: {{ $.Release.Namespace }}
spec: {{- include "cluster.internal.workers.kubeadmConfig.spec" $ | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
