{{- if $.Values.providerIntegration.resourcesApi.machinePoolResourcesEnabled }}
{{- if eq $.Values.providerIntegration.resourcesApi.nodePoolKind "MachineDeployment" }}
{{- range $nodePoolName, $nodePoolConfig := $.Values.global.nodePools | default $.Values.providerIntegration.workers.defaultNodePools }}
{{- if $nodePoolConfig.machineHealthCheck.enabled }}
{{- $_ := set $ "nodePool" (dict "name" $nodePoolName "config" $nodePoolConfig) }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  {{- $annotations := include "cluster.annotations.custom" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "cluster.labels.common" $ | nindent 4 }}
    {{- if $nodePoolConfig.labels }}
    {{- range $key, $val := $nodePoolConfig.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "cluster.resource.name" . }}-control-plane
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ include "cluster.resource.name" $ }}
  maxUnhealthy: {{ $nodePoolConfig.machineHealthCheck.maxUnhealthy }}
  nodeStartupTimeout: {{ $nodePoolConfig.machineHealthCheck.nodeStartupTimeout }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.resource.name" $ }}
      cluster.x-k8s.io/control-plane: ""
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: {{ $nodePoolConfig.machineHealthCheck.unhealthyUnknownTimeout }}
  - type: Ready
    status: "False"
    timeout: {{ $.nodePoolConfig.machineHealthCheck.unhealthyNotReadyTimeout }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
