{{- if $.Values.providerIntegration.resourcesApi.machinePoolResourcesEnabled }}
{{- if $.Values.providerIntegration.resourcesApi.machineHealthCheckResourceEnabled }}
{{- range $nodePoolName, $nodePoolConfig := $.Values.global.nodePools | default $.Values.providerIntegration.workers.defaultNodePools }}
{{- if $nodePoolConfig.machineHealthCheck }}
{{- if required "machineHealthCheck enabled property is required" $nodePoolConfig.machineHealthCheck.enabled }}
{{- if eq $.Values.providerIntegration.resourcesApi.nodePoolKind "MachineDeployment" }}
{{- $_ := set $ "nodePool" (dict "name" $nodePoolName "config" $nodePoolConfig) }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  {{- $annotations := include "cluster.annotations.custom" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    giantswarm.io/machine-deployment: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
    {{- include "cluster.labels.common" $ | nindent 4 }}
    {{- if $nodePoolConfig.labels }}
    {{- range $key, $val := $nodePoolConfig.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ include "cluster.resource.name" $ }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.resource.name" $ }}
      cluster.x-k8s.io/deployment-name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
  {{- $machineHealthCheck := dict "machineType" "workers" }}
  {{- $_ := mergeOverwrite $machineHealthCheck $nodePoolConfig.machineHealthCheck }}
  {{- include "cluster.internal.machinehealthcheck.commonspec" $machineHealthCheck | nindent 4 }}
{{- else if eq $.Values.providerIntegration.resourcesApi.nodePoolKind "MachinePool" }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  {{- $annotations := include "cluster.annotations.custom" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    giantswarm.io/machine-pool: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
    {{- include "cluster.labels.common" $ | nindent 4 }}
    {{- if $nodePoolConfig.labels }}
    {{- range $key, $val := $nodePoolConfig.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ include "cluster.resource.name" $ }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.resource.name" $ }}
      cluster.x-k8s.io/pool-name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
  {{- $machineHealthCheck := dict "machineType" "workers" }}
  {{- $_ := mergeOverwrite $machineHealthCheck $nodePoolConfig.machineHealthCheck }}
  {{- include "cluster.internal.machinehealthcheck.commonspec" $machineHealthCheck | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
