{{- if $.Values.providerIntegration.resourcesApi.machinePoolResourcesEnabled }}
{{- if eq $.Values.providerIntegration.resourcesApi.nodePoolKind "MachineDeployment" }}
{{- range $nodePoolName, $nodePoolConfig := $.Values.global.nodePools | default $.Values.providerIntegration.workers.defaultNodePools }}
{{- $_ := set $ "nodePool" (dict "name" $nodePoolName "config" $nodePoolConfig) }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    machine-deployment.giantswarm.io/name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
    {{- include "cluster.annotations.custom" $ | indent 4 }}
    {{- if $nodePoolConfig.annotations }}
    {{- range $key, $val := $nodePoolConfig.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "cluster.labels.common.all" $ | nindent 4 }}
    giantswarm.io/machine-deployment: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
    {{- if $nodePoolConfig.labels }}
    {{- range $key, $val := $nodePoolConfig.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ include "cluster.resource.name" $ }}
  replicas: {{ $nodePoolConfig.replicas }}
  {{- with $nodePoolConfig.strategy }}
  strategy:
    {{- with .rollingUpdate }}
    rollingUpdate:
      {{- if .deletePolicy }}
      deletePolicy: {{ .deletePolicy }}
      {{- end }}
      {{- if .maxSurge }}
      maxSurge: {{ .maxSurge }}
      {{- end }}
      {{- if .maxUnavailable }}
      maxUnavailable: {{ .maxUnavailable }}
      {{- end }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "cluster.labels.common" $ | nindent 8 }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}-{{ include "cluster.internal.workers.kubeadmConfig.spec.hash" $ }}
      clusterName: {{ include "cluster.resource.name" $ }}
      infrastructureRef:
        apiVersion: {{ $.Values.providerIntegration.resourcesApi.infrastructureMachinePool.group }}/{{ $.Values.providerIntegration.resourcesApi.infrastructureMachinePool.version }}
        kind: {{ $.Values.providerIntegration.resourcesApi.infrastructureMachinePool.kind }}
        {{- $_ := set $ "osImage" $.Values.providerIntegration.osImage }}
        {{- $_ = set $ "kubernetesVersion" $.Values.providerIntegration.kubernetesVersion }}
        name: {{ include "cluster.resource.name" $ }}-{{ $nodePoolName }}-{{ include "cluster.data.hash" (dict "data" (include $.Values.providerIntegration.workers.resources.infrastructureMachineTemplateSpecTemplateName $) "salt" $.Values.providerIntegration.hashSalt) }}
      version: v{{ include "cluster.component.kubernetes.version" $ }}
      {{- if hasKey $nodePoolConfig "failureDomain" }}
      failureDomain: "{{ $nodePoolConfig.failureDomain }}"
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
