global:
  metadata:
    name: awesome
    organization: giantswarm
  connectivity:
    baseDomain: example.gigantic.io
  nodePools:
    def00:
      minSize: 3
      maxSize: 20
    verybignodepool-1234:
      replicas: 100
providerIntegration:
  provider: aws
  resourcesApi:
    bastionResourceEnabled: false
    clusterResourceEnabled: true
    controlPlaneResourceEnabled: true
    infrastructureCluster:
      group: infrastructure.cluster.x-k8s.io
      kind: GiantCluster
      version: v1beta1
    machineHealthCheckResourceEnabled: true
    machinePoolResourcesEnabled: true
    nodePoolKind: MachinePool
    infrastructureMachinePool:
      group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: GiantMachinePool
    helmRepositoryResourcesEnabled: true
    verticalPodAutoscalerCrdHelmReleaseResourceEnabled: true
  controlPlane:
    resources:
      infrastructureMachineTemplate:
        group: infrastructure.cluster.x-k8s.io
        kind: GiantMachineTemplate
        version: v1beta1
      infrastructureMachineTemplateSpecTemplateName: cluster.internal.test.controlPlane.machineTemplate.spec
  workers:
    defaultNodePools:
      def00:
        customNodeLabels:
        - label=default
        maxSize: 3
        minSize: 3
