global:
  managementCluster: giantmc
  release:
    version: v27.0.0-alpha.1
  metadata:
    name: awesome
    organization: giantswarm
    description: "Awesome Giant Swarm cluster"
  connectivity:
    baseDomain: example.gigantic.io
  nodePools:
    def00:
      cgroupsv1: false
      replicas: 3
    def01:
      cgroupsv1: true
      replicas: 3
    def02:
      cgroupsv1: false
      replicas: 3
providerIntegration:
  provider: aws
  workers:
    defaultNodePools:
      def00:
        customNodeLabels:
          - label=default
        maxSize: 3
        minSize: 3
  components:
    containerd:
      sandboxContainerImage:
        name: giantswarm/pause
        tag: "3.9"
  resourcesApi:
    clusterResourceEnabled: true
    controlPlaneResourceEnabled: true
    machinePoolResourcesEnabled: true
    machineHealthCheckResourceEnabled: true
    bastionResourceEnabled: true
    infrastructureCluster:
      group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: AWSCluster
    nodePoolKind: MachinePool
    infrastructureMachinePool:
      group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: AWSMachinePool
    helmRepositoryResourcesEnabled: true
    bastion:
      infrastructureMachineTemplate:
        group: infrastructure.cluster.x-k8s.io
        version: v1beta1
        kind: AWSMachineTemplate
      infrastructureMachineTemplateSpecTemplateName: "cluster.test.bastion.machineTemplate.spec"
  controlPlane:
    resources:
      infrastructureMachineTemplate:
        group: infrastructure.cluster.x-k8s.io
        kind: GiantMachineTemplate
        version: v1beta1
      infrastructureMachineTemplateSpecTemplateName: cluster.internal.test.controlPlane.machineTemplate.spec
