appName: cert-exporter
configKey: certExporter
dependsOn:
- kyverno-crds
- kyverno
namespace: kube-system
# used by renovate
# repo: giantswarm/cert-exporter
version: 2.11.0
defaultValues:
  ciliumNetworkPolicy:
    enabled: true
