appName: cert-exporter
configKey: certExporter
dependsOn: kyverno-crds
namespace: kube-system
# used by renovate
# repo: giantswarm/cert-exporter
version: 2.10.1
defaultValues:
  ciliumNetworkPolicy:
    enabled: true
