appName: cert-manager
chartName: cert-manager-app
configKey: certManager
# repo: giantswarm/cert-manager-app
version: 4.0.1
dependsOn:
- alloy-podlogs-crds
- prometheus-operator-crd

namespace: kube-system
defaultValues:
  ciliumNetworkPolicy:
    enabled: true
  # Authoritative nameservers aren't reachable in private clusters, use the resolver instead.
  dns01RecursiveNameserversOnly: true
  ingressShim:
    defaultIssuerGroup: cert-manager.io
    defaultIssuerKind: ClusterIssuer
    defaultIssuerName: letsencrypt-giantswarm
  {{- if .Values.global.connectivity.proxy.enabled }}
  http_proxy: {{ .Values.global.connectivity.proxy.httpProxy | quote }}
  https_proxy: {{ .Values.global.connectivity.proxy.httpsProxy | quote }}
  no_proxy: {{ include "cluster.connectivity.proxy.noProxy" (dict "global" .Values.global "providerIntegration" .Values.providerIntegration) | quote }}
  {{- end }}
