appName: cert-manager
chartName: cert-manager-app
configKey: certManager
dependsOn:
  - prometheus-operator-crd
  - kube-prometheus-stack
namespace: kube-system
# used by renovate
# repo: giantswarm/cert-manager-app
version: 3.12.0
defaultValues:
  # cert-manager's DNS01 solver by default tries to reach authoritative nameservers directly, using
  # their public IPs. Since those are not reachable from private clusters, we instead rely on the
  # recursive nameserver (e.g. for AWS, that's normally the default nameserver requested in EC2 instances).
  dns01RecursiveNameserversOnly: true
  ingressShim:
    defaultIssuerName: letsencrypt-giantswarm
    defaultIssuerKind: ClusterIssuer
    defaultIssuerGroup: cert-manager.io
  ciliumNetworkPolicy:
    enabled: true
  {{- if .Values.global.connectivity.proxy.enabled }}
  no_proxy: {{ include "cluster.connectivity.proxy.noProxy" (dict "global" .Values.global "providerIntegration" .Values.providerIntegration) | quote }}
  http_proxy: {{ .Values.global.connectivity.proxy.httpProxy | quote }}
  https_proxy: {{ .Values.global.connectivity.proxy.httpsProxy | quote }}
  {{- end }}
