appName: cert-manager-crossplane-resources
configKey: certManagerCrossplaneResources
namespace: {{ .Release.Namespace }}
useOCISource: true
# repo: giantswarm/cert-manager-crossplane-resources
version: 0.1.2-dev.add-workload-identity.2026-07-30.07-23-15.h5bc8573

prependClusterName: true
skipKubeConfig: true
serviceAccountName: automation

defaultValues:
  provider: {{ .Values.providerIntegration.provider }}
  clusterName: {{ include "cluster.resource.name" . }}
