appName: cert-manager-crossplane-resources
# repo: giantswarm/cert-manager-crossplane-resources
version: 0.2.0

inCluster: true

defaultValues:
  provider: {{ .Values.providerIntegration.provider }}
  clusterName: {{ include "cluster.resource.name" . }}
