appName: cilium
# repo: giantswarm/cilium-app
version: 1.5.1

timeout: 1h
remediationRetries: 0

namespace: kube-system
defaultValues:
  ipam:
    mode: kubernetes
  k8sServiceHost: auto
  kubeProxyReplacement: "true"
  hubble:
    relay:
      tolerations:
      - operator: Exists
    ui:
      tolerations:
      - operator: Exists
  certgen:
    tolerations:
    - operator: Exists
  # Configured by provider.
  defaultPolicies: {}
  # Configured by provider.
  extraPolicies: {}
