appName: cilium
configKey: cilium
# repo: giantswarm/cilium-app
version: 1.4.5

timeout: 1h
remediationRetries: 0

namespace: kube-system
defaultValues:
  ipam:
    mode: kubernetes
  k8sServiceHost: auto
  kubeProxyReplacement: "true"
  hubble:
    relay:
      enabled: true
      # Configured by provider.
      tolerations: []
    # Configured by provider.
    ui: {}
  # Configured by provider.
  defaultPolicies: {}
  # Configured by provider.
  extraPolicies: {}
