appName: cilium
# repo: giantswarm/cilium-app
version: 1.6.0

timeout: 1h
remediationRetries: 0

namespace: kube-system
defaultValues:
  ipam:
    mode: kubernetes
  k8sServiceHost: auto
  kubeProxyReplacement: "true"
  operator:
    tolerations:
      {{- include "cluster.internal.apps.cilium.tolerations" $ | nindent 6 }}
  hubble:
    relay:
      tolerations:
        {{- include "cluster.internal.apps.cilium.tolerations" $ | nindent 8 }}
    ui:
      tolerations:
        {{- include "cluster.internal.apps.cilium.tolerations" $ | nindent 8 }}
  certgen:
    tolerations:
      {{- include "cluster.internal.apps.cilium.tolerations" $ | nindent 6 }}
  # Configured by provider.
  defaultPolicies: {}
  # Configured by provider.
  extraPolicies: {}
