appName: cluster-autoscaler
chartName: cluster-autoscaler-app
configKey: clusterAutoscaler
# repo: giantswarm/cluster-autoscaler-app
version: 2.0.1
{{- if ne $.Values.providerIntegration.provider "azure" }}
dependsOn:
- kyverno-crds
{{- end }}

{{- if eq $.Values.providerIntegration.provider "azure" }}
inCluster: true
{{- end }}

{{- if ne $.Values.providerIntegration.provider "azure" }}
namespace: kube-system
{{- end }}
defaultValues:
  clusterID: {{ include "cluster.resource.name" $ }}
  provider: {{ .Values.providerIntegration.provider }}
  {{- if .Values.global.connectivity.proxy.enabled }}
  proxy:
    http: {{ .Values.global.connectivity.proxy.httpProxy | quote }}
    https: {{ .Values.global.connectivity.proxy.httpsProxy | quote }}
    noProxy: {{ include "cluster.connectivity.proxy.noProxy" (dict "global" .Values.global "providerIntegration" .Values.providerIntegration) | quote }}
  {{- end }}
