appName: cluster-autoscaler
chartName: cluster-autoscaler-app
configKey: clusterAutoscaler
inCluster: {{ eq $.Values.providerIntegration.provider "azure" }}
{{- if ne $.Values.providerIntegration.provider "azure" }}
dependsOn:
- kyverno-crds
{{- end }}
namespace: kube-system
# used by renovate
# repo: giantswarm/cluster-autoscaler-app
version: 2.0.3
defaultValues:
  clusterID: {{ include "cluster.resource.name" $ }}
  provider: {{ .Values.providerIntegration.provider }}
  {{- if .Values.global.connectivity.proxy.enabled }}
  cluster:
    proxy:
      noProxy: {{ include "cluster.connectivity.proxy.noProxy" (dict "global" .Values.global "providerIntegration" .Values.providerIntegration) | quote }}
      http: {{ .Values.global.connectivity.proxy.httpProxy | quote }}
      https: {{ .Values.global.connectivity.proxy.httpsProxy | quote }}
  {{- end }}
