appName: coredns
chartName: coredns-app
configKey: coreDns
namespace: kube-system
# used by renovate
# repo: giantswarm/coredns-app
version: 1.31.0
dependsOn: {{ if not (eq $.Values.providerIntegration.provider "aks") }}["cilium"]{{ else }}[]{{ end }}
defaultValues:
  coredns:
    cluster:
      podCIDR: {{ first .Values.global.connectivity.network.pods.cidrBlocks | quote }}
      serviceCIDR: {{ first .Values.global.connectivity.network.services.cidrBlocks | quote }}
  service:
    clusterIP: {{ include "cluster.internal.apps.coredns.dns" $ | quote }}
  global:
    podSecurityStandards:
      enforced: {{ .Values.global.podSecurityStandards.enforced }}
  controlPlane:
    enabled: {{ include "cluster.internal.apps.coredns.mastersInstance.enabled" $ }}
