appName: coredns
chartName: coredns-app
configKey: coreDns
# repo: giantswarm/coredns-app
version: 1.31.0
{{- if ne $.Values.providerIntegration.provider "aks" }}
dependsOn:
- cilium
{{- end }}

namespace: kube-system
defaultValues:
  coredns:
    cluster:
      podCIDR: {{ first .Values.global.connectivity.network.pods.cidrBlocks | quote }}
      serviceCIDR: {{ first .Values.global.connectivity.network.services.cidrBlocks | quote }}
  service:
    clusterIP: {{ include "cluster.internal.apps.coredns.dns" $ | quote }}
  global:
    podSecurityStandards:
      enforced: {{ .Values.global.podSecurityStandards.enforced }}
  controlPlane:
    enabled: {{ include "cluster.internal.apps.coredns.controlPlane.enabled" $ }}
