appName: external-dns-crossplane-resources
configKey: externalDnsCrossplaneResources
namespace: {{ .Release.Namespace }}
useOCISource: true
# repo: giantswarm/external-dns-crossplane-resources
version: 1.0.0

prependClusterName: true
skipKubeConfig: true
serviceAccountName: automation

defaultValues:
  provider:
    name: {{ .Values.providerIntegration.provider }}
  cluster:
    name: {{ include "cluster.resource.name" . }}
