appName: k8s-dns-node-cache
chartName: k8s-dns-node-cache-app
# repo: giantswarm/k8s-dns-node-cache-app
version: 2.11.0
dependsOn:
- cilium
- kyverno-crds
- prometheus-operator-crd

namespace: kube-system
