appName: kamaji-etcd
configKey: kamajiEtcd
# repo: giantswarm/kamaji-etcd-app
version: 0.3.1

disable: {{ include "kamaji.isEnabled" $ | ne "true" }}
inCluster: true
interval: 1m
additionalAnnotations:
  helm.sh/resource-policy: keep

defaultValues:
  persistentVolumeClaim:
    retentionPolicyWhenDeleted: Delete
  datastore:
    name: {{ include "cluster.resource.name" $ }}
