appName: metrics-server
chartName: metrics-server-app
configKey: metricsServer
# repo: giantswarm/metrics-server-app
version: 2.8.0
dependsOn:
- kyverno-crds

namespace: kube-system
defaultValues:
  provider: {{ .Values.providerIntegration.provider }}
  ciliumNetworkPolicy:
    enabled: true
