appName: metrics-server
chartName: metrics-server-app
# repo: giantswarm/metrics-server-app
version: 2.8.0
dependsOn:
- cilium
- kyverno-crds
- vertical-pod-autoscaler-crd

namespace: kube-system
defaultValues:
  provider: {{ .Values.providerIntegration.provider }}
  ciliumNetworkPolicy:
    enabled: true
