appName: network-policies
configKey: networkPolicies
# repo: giantswarm/network-policies-app
version: 0.2.0
{{- if ne $.Values.providerIntegration.provider "aks" }}
dependsOn:
- cilium
{{- end }}

disable: {{ .Values.global.connectivity.network.allowAllEgress }}
interval: 1m

namespace: kube-system
