appName: node-exporter
chartName: node-exporter-app
# repo: giantswarm/node-exporter-app
version: 1.21.0
dependsOn:
- kyverno-crds
- prometheus-operator-crd
- vertical-pod-autoscaler-crd

namespace: kube-system
