appName: node-problem-detector
configKey: nodeProblemDetector
# repo: giantswarm/node-problem-detector-app
version: 0.5.2
dependsOn:
- kyverno-crds
- prometheus-operator-crd

disable: {{ include "cluster.internal.machinehealthcheck.use-node-problem-detector" $ | ne "true" }}
interval: 1m

namespace: kube-system
