appName: observability-bundle
# repo: giantswarm/observability-bundle
version: 3.4.0

inCluster: true
driftDetection: enabled

defaultValues:
  managementCluster: {{ $.Values.global.managementCluster }}
  clusterID: {{ include "cluster.resource.name" $ }}
