appName: prometheus-blackbox-exporter
configKey: prometheusBlackboxExporter
# repo: giantswarm/prometheus-blackbox-exporter
version: 0.8.0
dependsOn:
- prometheus-operator-crd

namespace: kube-system
