appName: prometheus-blackbox-exporter
configKey: prometheusBlackboxExporter
dependsOn: prometheus-operator-crd
namespace: kube-system
# used by renovate
# repo: giantswarm/prometheus-blackbox-exporter
version: 0.7.0
