appName: security-bundle
configKey: securityBundle
catalog: giantswarm
dependsOn: prometheus-operator-crd
inCluster: true
namespace: kube-system
driftDetection: enabled
# used by renovate
# repo: giantswarm/security-bundle
version: 2.0.0
defaultValues:
  clusterID: {{ include "cluster.resource.name" $ }}
