{{- /* Default values */}}
{{- /* https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml */}}
{{- define "cluster.internal.apps.cilium.config.default" }}
ipam:
  mode: kubernetes
k8sServiceHost: api.{{ include "cluster.resource.name" $ }}.{{ .Values.global.connectivity.baseDomain }}
k8sServicePort: '{{ .Values.global.controlPlane.apiServerPort }}'
kubeProxyReplacement: strict
hubble:
  relay:
    enabled: true
    tolerations: [] # set in cluster-<provider> apps
  ui: {} # set by cluster-<provider> apps
defaultPolicies: {} # set in cluster-<provider> apps
extraPolicies: {} # set in cluster-<provider> apps
global:
  podSecurityStandards:
    enforced: {{ .Values.global.podSecurityStandards.enforced }}
{{- end }}
{{- if $.Values.providerIntegration.resourcesApi.ciliumHelmReleaseResourceEnabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "cluster.resource.name" $ }}-cilium
  namespace: {{ $.Release.Namespace }}
  {{- $annotations := include "cluster.annotations.common.all" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "cluster.labels.common.all" $ | indent 4 }}
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cilium
      # used by renovate
      # repo: giantswarm/cilium-app
      version: 0.21.0
      sourceRef:
        kind: HelmRepository
        name: {{ include "cluster.resource.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "cluster.resource.name" $ }}-kubeconfig
  interval: 5m
  install:
    remediation:
      retries: 30
  {{- /* Default provider-independent cilium config */}}
  {{- $ciliumHelmValues := (include "cluster.internal.apps.cilium.config.default" $) | fromYaml -}}
  {{- /* Default provider-specific cilium config will override provider-independent cilium config */}}
  {{- if $.Values.providerIntegration.apps.cilium.configTemplateName }}
  {{- $providerSpecificCiliumHelmValues := (include $.Values.providerIntegration.apps.cilium.configTemplateName $) | fromYaml -}}
  {{- $ciliumHelmValues = mergeOverwrite $ciliumHelmValues (deepCopy $providerSpecificCiliumHelmValues) -}}
  {{- end }}
  {{- /* Custom user config will override both default provider-specific and provider-independent cilium config */}}
  {{- $customCiliumHelmValues := $.Values.global.apps.cilium.values -}}
  {{- if $customCiliumHelmValues }}
  {{- $ciliumHelmValues = mergeOverwrite $ciliumHelmValues (deepCopy $customCiliumHelmValues) -}}
  {{- end }}
  {{- if $ciliumHelmValues }}
  values: {{- $ciliumHelmValues | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.apps.cilium.extraConfigs }}
  valuesFrom:
    {{- range $config := $.Values.global.apps.cilium.extraConfigs }}
  - kind: {{ $config.kind }}
    name: {{ $config.name }}
    valuesKey: values
    optional: {{ $config.optional | default false  }}
    {{- end }}
  {{- end }}
{{- end }}
