{{- if or $.Values.providerIntegration.apps.cilium.enable $.Values.providerIntegration.resourcesApi.ciliumHelmReleaseResourceEnabled }}
{{- $app := tpl (.Files.Get "files/helmreleases/cilium.yaml") $ | fromYaml }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "cluster.resource.name" $ }}-{{ $app.appName }}
  namespace: {{ $.Release.Namespace }}
  {{- $annotations := include "cluster.annotations.common.all" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "cluster.labels.common.all" $ | indent 4 }}
spec:
  releaseName: {{ $app.appName }}
  targetNamespace: {{ $app.namespace }}
  storageNamespace: {{ $app.namespace }}
  chart:
    spec:
      chart: {{ $app.chartName }}
      version: {{ $app.version }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "cluster.resource.name" $ }}-{{ $app.catalog }}
  kubeConfig:
    secretRef:
      name: {{ include "cluster.resource.name" $ }}-kubeconfig
  interval: 5m
  install:
    remediation:
      retries: 30
  {{- /* Default provider-independent cilium config */}}
  {{- $ciliumHelmValues := (include "cluster.internal.apps.cilium.config.default" $) | fromYaml -}}
  {{- /* Default provider-specific cilium config will override provider-independent cilium config */}}
  {{- if $.Values.providerIntegration.apps.cilium.configTemplateName }}
  {{- $providerSpecificCiliumHelmValues := (include $.Values.providerIntegration.apps.cilium.configTemplateName $) | fromYaml -}}
  {{- $ciliumHelmValues = mergeOverwrite $ciliumHelmValues (deepCopy $providerSpecificCiliumHelmValues) -}}
  {{- end }}
  {{- /* Custom user config will override both default provider-specific and provider-independent cilium config */}}
  {{- $customCiliumHelmValues := $.Values.global.apps.cilium.values -}}
  {{- if $customCiliumHelmValues }}
  {{- $ciliumHelmValues = mergeOverwrite $ciliumHelmValues (deepCopy $customCiliumHelmValues) -}}
  {{- end }}
  {{- if $ciliumHelmValues }}
  values: {{- $ciliumHelmValues | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.apps.cilium.extraConfigs }}
  valuesFrom:
    {{- range $config := $.Values.global.apps.cilium.extraConfigs }}
  - kind: {{ $config.kind }}
    name: {{ $config.name }}
    valuesKey: values
    optional: {{ $config.optional | default false  }}
    {{- end }}
  {{- end }}
{{- end }}
