{{/* Default Helm values for the app */}}
{{/* See schema for the appropriate app version here https://github.com/giantswarm/coredns-app/blob/main/helm/coredns-app/values.schema.json */}}
{{- define "cluster.internal.apps.coredns.config.default" }}
cluster:
  calico:
    CIDR: {{ first .Values.global.connectivity.network.pods.cidrBlocks | quote }}
  kubernetes:
    API:
      clusterIPRange: {{ first .Values.global.connectivity.network.services.cidrBlocks | quote }}
    DNS:
      IP: {{ include "cluster.internal.apps.coredns.dns" $ | quote }}
global:
  podSecurityStandards:
    enforced: {{ .Values.global.podSecurityStandards.enforced }}
{{- end }}
{{- if $.Values.providerIntegration.resourcesApi.coreDnsHelmReleaseResourceEnabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "cluster.resource.name" $ }}-coredns
  namespace: {{ $.Release.Namespace }}
  {{- $annotations := include "cluster.annotations.common.all" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "cluster.labels.common.all" $ | indent 4 }}
spec:
  releaseName: coredns
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: coredns-app
      # used by renovate
      # repo: giantswarm/coredns-app
      version: 1.21.0
      sourceRef:
        kind: HelmRepository
        name: {{ include "cluster.resource.name" $ }}-default
  dependsOn:
      - name: {{ include "cluster.resource.name" $ }}-cilium
        namespace: {{ $.Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "cluster.resource.name" $ }}-kubeconfig
  interval: 5m
  install:
    remediation:
      retries: 30
  {{- $coreDnsHelmValues := (include "cluster.internal.apps.coredns.config.default" .) | fromYaml -}}
  {{- $customCoreDnsHelmValues := $.Values.global.apps.coreDns.values -}}
  {{- if $customCoreDnsHelmValues }}
  {{- $coreDnsHelmValues = mergeOverwrite $coreDnsHelmValues (deepCopy $customCoreDnsHelmValues) -}}
  {{- end }}
  {{- if $coreDnsHelmValues }}
  values: {{- $coreDnsHelmValues | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.apps.coreDns.extraConfigs }}
  valuesFrom:
  {{- range $config := $.Values.global.apps.coreDns.extraConfigs }}
  - kind: {{ $config.kind }}
    name: {{ $config.name }}
    valuesKey: values
    optional: {{ $config.optional | default false  }}
  {{- end }}
  {{- end }}
{{- end }}
