{{- /* Default values */}}
{{- /* https://github.com/giantswarm/network-policies-app/blob/main/helm/network-policies-app/values.yaml */}}
{{- define "cluster.internal.apps.networkPolicies.config.default" }}
{{- end }}
{{- if .Values.providerIntegration.resourcesApi.networkPoliciesHelmReleaseResourceEnabled }}
{{- if not .Values.global.connectivity.network.allowAllEgress }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "cluster.resource.name" $ }}-network-policies
  namespace: {{ $.Release.Namespace }}
  {{- $annotations := include "cluster.annotations.common.all" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "cluster.labels.common.all" $ | indent 4 }}
spec:
  releaseName: network-policies
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: network-policies
      version: 0.0.4-d898c7da8286d6f23eecec1f8fb780da3499f124
      sourceRef:
        kind: HelmRepository
        name: {{ include "cluster.resource.name" $ }}-cluster-test
  dependsOn:
  - name: {{ include "cluster.resource.name" $ }}-cilium
    namespace: {{ $.Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "cluster.resource.name" $ }}-kubeconfig
  interval: 1m
  install:
    remediation:
      retries: 30
  # Default values
  {{- /* Default provider-independent networkPolicies config */}}
  {{- $networkPoliciesHelmValues := (include "cluster.internal.apps.networkPolicies.config.default" $) | fromYaml -}}
  {{- /* Default provider-specific networkPolicies config will override provider-independent networkPolicies config */}}
  {{- if $.Values.providerIntegration.apps.networkPolicies.configTemplateName }}
  {{- $providerSpecificNetworkPoliciesHelmValues := (include $.Values.providerIntegration.apps.networkPolicies.configTemplateName $) | fromYaml -}}
  {{- $networkPoliciesHelmValues = mergeOverwrite $networkPoliciesHelmValues (deepCopy $providerSpecificNetworkPoliciesHelmValues) -}}
  {{- end }}
  {{- /* Custom user config will override both default provider-specific and provider-independent networkPolicies config */}}
  {{- $customNetworkPoliciesHelmValues := $.Values.global.apps.networkPolicies.values -}}
  {{- if $customNetworkPoliciesHelmValues }}
  {{- $networkPoliciesHelmValues = mergeOverwrite $networkPoliciesHelmValues (deepCopy $customNetworkPoliciesHelmValues) -}}
  {{- end }}
  {{- if $networkPoliciesHelmValues }}
  values: {{- $networkPoliciesHelmValues | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
