{{- if $.Values.providerIntegration.resourcesApi.verticalPodAutoscalerCrdHelmReleaseEnabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "cluster.resource.name" $ }}-vertical-pod-autoscaler-crd
  namespace: {{ $.Release.Namespace }}
  {{- $annotations := include "cluster.annotations.common.all" $ }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "cluster.labels.common.all" $ | indent 4 }}
spec:
  releaseName: vertical-pod-autoscaler-crd
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: vertical-pod-autoscaler-crd
      # used by renovate
      # repo: giantswarm/vertical-pod-autoscaler-crd
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: {{ include "cluster.resource.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "cluster.resource.name" $ }}-kubeconfig
  interval: 1m
  install:
    remediation:
      retries: 30
  {{- $customVerticalPodAutoscalerCrdHelmValues := $.Values.global.apps.verticalPodAutoscalerCrd.values -}}
  {{- if $customVerticalPodAutoscalerCrdHelmValues }}
  values: {{- $customVerticalPodAutoscalerCrdHelmValues | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.apps.verticalPodAutoscalerCrd.extraConfigs }}
  valuesFrom:
  {{- range $config := $.Values.global.apps.verticalPodAutoscalerCrd.extraConfigs }}
  - kind: {{ $config.kind }}
    name: {{ $config.name }}
    valuesKey: values
    optional: {{ $config.optional | default false  }}
  {{- end }}
  {{- end }}
{{- end }}
