{{- if .Values.providerIntegration.resourcesApi.cleanupHelmReleaseResourcesEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cluster.resource.name" . }}-helmreleases-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "cluster.labels.common.all" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cluster.resource.name" . }}-helmreleases-cleanup
subjects:
- kind: ServiceAccount
  name: {{ include "cluster.resource.name" . }}-helmreleases-cleanup
  namespace: {{ .Release.Namespace }}
{{- end }}
