{{- if .Values.providerIntegration.resourcesApi.cleanupHelmReleaseResourcesEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cluster.resource.name" . }}-helmreleases-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "cluster.labels.common.all" . | nindent 4 }}
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - list
  - get
  - patch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  - helmcharts/finalizers
  verbs:
  - list
  - get
  - patch
  - delete
{{- end }}
