{{- if .Values.providerIntegration.resourcesApi.cleanupHelmReleaseResourcesEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster.resource.name" . }}-helmreleases-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "cluster.labels.common.all" . | nindent 4 }}
{{- end }}
