appName: capi-node-labeler
chartName: capi-node-labeler
configKey: capiNodeLabeler
catalog: default
clusterValues:
  configMap: true
  secret: false
enabled: true
namespace: kube-system
# used by renovate
# repo: giantswarm/capi-node-labeler-app
version: 0.5.0
