appName: capi-node-labeler
configKey: capiNodeLabeler
clusterValues:
  configMap: true
  secret: false
namespace: kube-system
# used by renovate
# repo: giantswarm/capi-node-labeler-app
version: 1.1.0
