appName: cert-manager
chartName: cert-manager-app
configKey: certManager
catalogs: control-plane-test
clusterValues:
  configMap: true
  secret: true
dependsOn: prometheus-operator-crd
namespace: kube-system
# used by renovate
# repo: giantswarm/cert-manager-app
version: 3.9.0-7b31edf02e7a30ec1aa6bd60b15fb5f717710ebd
defaultValues:
  # cert-manager's DNS01 solver by default tries to reach authoritative nameservers directly, using
  # their public IPs. Since those are not reachable from private clusters, we instead rely on the
  # recursive nameserver (e.g. for AWS, that's normally the default nameserver requested in EC2 instances).
  dns01RecursiveNameserversOnly: true
  ingressShim:
    defaultIssuerName: letsencrypt-giantswarm
    defaultIssuerKind: ClusterIssuer
    defaultIssuerGroup: cert-manager.io
  ciliumNetworkPolicy:
    enabled: true
