appName: cert-manager-bundle
configKey: certManager
clusterValues:
  configMap: true
  secret: true
inCluster: true
dependsOnHelmRelease: true
dependsOn: prometheus-operator-crd
namespace: kube-system
# used by renovate
# repo: giantswarm/cert-manager-bundle
version: 0.0.1
