appName: cluster-autoscaler
chartName: cluster-autoscaler-app
configKey: clusterAutoscaler
clusterValues:
  configMap: true
  secret: true
dependsOn: kyverno-crds
namespace: kube-system
# used by renovate
# repo: giantswarm/cluster-autoscaler-app
version: 1.30.4-gs1
{{- if include "hasKarpenterNodePool" . }}
defaultValues:
  configmap:
    newPodScaleUpDelay: 300s
{{- end }}
