appName: etcd-defrag
configKey: etcdDefrag
clusterValues:
  configMap: false
  secret: false
dependsOn: kyverno-crds
namespace: kube-system
# used by renovate
# repo: giantswarm/etcd-defrag-app
version: 1.0.5
defaultValues:
  etcdStorageQuotaBytes: {{ mul $.Values.internal.advancedConfiguration.controlPlane.etcd.quotaBackendBytesGiB 1024 1024 1024 }}
