appName: external-dns
chartName: external-dns-app
configKey: externalDns
clusterValues:
  configMap: true
  secret: true
dependsOn: prometheus-operator-crd
namespace: kube-system
# used by renovate
# repo: giantswarm/external-dns-app
version: 3.1.0
defaultValues:
  provider: {{ .Values.providerIntegration.provider }}
  domainFilters:
  - {{ include "cluster.internal.apps.baseDomain" . }}
  txtOwnerId: giantswarm-io-external-dns
  txtPrefix: {{ $.Values.global.metadata.name }}
  registry: txt
  annotationFilter: giantswarm.io/external-dns=managed
  sources:
  - service
  ciliumNetworkPolicy:
    enabled: true
