appName: net-exporter
chartName: net-exporter
configKey: netExporter
catalog: default
clusterValues:
  configMap: true
  secret: false
dependsOn: prometheus-operator-crd
namespace: kube-system
# used by renovate
# repo: giantswarm/net-exporter
version: 1.18.2
defaultValues:
  ciliumNetworkPolicy:
    enabled: true
  {{- if ($.Values.providerIntegration.components.systemd).timesyncd }}
  NetExporter:
    NTPServers: {{ join "," (compact $.Values.providerIntegration.components.systemd.timesyncd.ntp) }}
  {{- end }}
