appName: net-exporter
configKey: netExporter
clusterValues:
  configMap: true
  secret: false
dependsOn: prometheus-operator-crd
namespace: kube-system
# used by renovate
# repo: giantswarm/net-exporter
version: 1.23.0
defaultValues:
  ciliumNetworkPolicy:
    enabled: true
  DNSCheck:
    TCP:
      Disabled: false
  Hosts: giantswarm.io.,kubernetes.default.svc.cluster.local.
  NetExporter:
  {{- if ($.Values.providerIntegration.components.systemd).timesyncd }}
    NTPServers: {{ join "," (compact $.Values.providerIntegration.components.systemd.timesyncd.ntp) }}
  {{- else }}
    NTPServers: 0.flatcar.pool.ntp.org.,1.flatcar.pool.ntp.org.
  {{- end }}
