# Includes prometheus-operator-crd
appName: observability-bundle
configKey: observabilityBundle
clusterValues:
  configMap: true
  secret: false
inCluster: true
dependsOnHelmRelease: true
dependsOn: {{ if not (eq $.Values.providerIntegration.provider "aks") }}["coredns"]{{ else }}[]{{ end }}
namespace: kube-system
# used by renovate
# repo: giantswarm/observability-bundle
version: 3.0.0
defaultValues:
  managementCluster: {{ $.Values.global.managementCluster }}
