appName: security-bundle
configKey: securityBundle
catalog: giantswarm
clusterValues:
  configMap: true
  secret: false
dependsOn: prometheus-operator-crd
inCluster: true
namespace: kube-system
# used by renovate
# repo: giantswarm/security-bundle
version: 1.11.0
