appName: teleport-kube-agent
configKey: teleportKubeAgent
clusterValues:
  configMap: true
  secret: true
forceUpgrade: true
namespace: kube-system
# used by renovate
# repo: giantswarm/teleport-kube-agent-app
version: 0.10.2
# a list of extraConfigs for the App,
# It can be secret or configmap
# https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
extraConfigs:
- kind: configMap
  name: "{{ $.Values.global.metadata.name }}-teleport-kube-agent-config"
  namespace: "{{ $.Release.Namespace }}"
