appName: vertical-pod-autoscaler
chartName: vertical-pod-autoscaler-app
configKey: verticalPodAutoscaler
catalog: default
dependsOn: prometheus-operator-crd
clusterValues:
  configMap: true
  secret: false
enabled: true
namespace: kube-system
# used by renovate
# repo: giantswarm/vertical-pod-autoscaler-app
version: 5.1.0
