appName: vertical-pod-autoscaler
chartName: vertical-pod-autoscaler-app
configKey: verticalPodAutoscaler
dependsOn: prometheus-operator-crd
clusterValues:
  configMap: true
  secret: false
namespace: kube-system
# used by renovate
# repo: giantswarm/vertical-pod-autoscaler-app
version: 5.2.4
