apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    {{- with .Values.metadata.description }}
    cluster.giantswarm.io/description: "{{ . }}"
    {{- end }}
  labels:
    {{- include "cluster.labels.common" $ | nindent 4 }}
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- if .Values.metadata.labels }}
    {{- range $key, $val := .Values.metadata.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  name: {{ include "cluster.resource.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      {{- toYaml $.Values.global.connectivity.network.services.cidrBlocks | nindent 8 }}
    pods:
      cidrBlocks:
      {{- toYaml $.Values.global.connectivity.network.pods.cidrBlocks | nindent 8 }}
  controlPlaneRef:
    apiVersion: {{ .Values.internal.controlPlane.resources.controlPlane.api.group }}/{{ .Values.internal.controlPlane.resources.controlPlane.api.version }}
    kind: {{ .Values.internal.controlPlane.resources.controlPlane.api.kind }}
    name: {{ include "cluster.resource.name" $ }}
  infrastructureRef:
    apiVersion: {{ .Values.internal.providerSpecific.resources.cluster.api.group }}/{{ .Values.internal.providerSpecific.resources.cluster.api.version }}
    kind: {{ .Values.internal.providerSpecific.resources.cluster.api.kind }}
    name: {{ include "cluster.resource.name" $ }}
  {{- if .Values.internal.paused }}
  paused: true
  {{- end -}}
