{{- if $.Values.providerIntegration.resourcesApi.clusterResourceEnabled }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    {{- with $.Values.global.metadata.description }}
    cluster.giantswarm.io/description: "{{ . }}"
    {{- end }}
    {{- if .Values.providerIntegration.clusterAnnotationsTemplateName }}
    {{- include .Values.providerIntegration.clusterAnnotationsTemplateName $ | indent 4 }}
    {{- end }}
    {{- include "cluster.annotations.custom" $ | indent 4 }}
  labels:
    {{- include "cluster.labels.common" $ | nindent 4 }}
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "cluster.labels.custom" $ | indent 4 }}
  name: {{ include "cluster.resource.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      {{- toYaml $.Values.global.connectivity.network.services.cidrBlocks | nindent 8 }}
    pods:
      cidrBlocks:
      {{- toYaml $.Values.global.connectivity.network.pods.cidrBlocks | nindent 8 }}
  controlPlaneRef:
    apiVersion: {{ .Values.providerIntegration.controlPlane.resources.controlPlane.api.group }}/{{ .Values.providerIntegration.controlPlane.resources.controlPlane.api.version }}
    kind: {{ .Values.providerIntegration.controlPlane.resources.controlPlane.api.kind }}
    name: {{ include "cluster.resource.name" $ }}
  infrastructureRef:
    {{- with .Values.providerIntegration.resourcesApi.infrastructureCluster }}
    apiVersion: {{ .group }}/{{ .version }}
    kind: {{ .kind }}
    {{- end }}
    name: {{ include "cluster.resource.name" $ }}
  {{- $paused := false }}
  {{- range $propertyPath, $propertyPauseValue := .Values.providerIntegration.pauseProperties }}
  {{- $propertyValue := (include "cluster.values.get" (dict "Values" $.Values "path" $propertyPath)) | trim }}
  {{- $triggersPause := (include "cluster.values.equal" (dict "Values" $.Values "path" $propertyPath "testValue" $propertyPauseValue )) | trim }}
  {{- $paused = or $paused (eq $triggersPause "true") }}
  {{- end }}
  {{- if $paused }}
  paused: true
  {{- end }}
{{- end }}
