{{- if or $.Values.internal.resourcesApi.controlPlaneResourceEnabled $.Values.internal.resourcesApi.machinePoolResourcesEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster.resource.name" $ }}-registry-configuration
data:
  registry-config.toml: {{ tpl ($.Files.Get "files/etc/containerd/config.toml") $ | b64enc | quote }}
{{- end }}
