name: Run manifest tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Check if there were any changes in the cluster chart
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect_changes.outputs.changes }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for changes in helm/cluster
      id: detect_changes
      run: |
        if git diff --name-only main ${{ github.sha }} | grep '^helm/cluster/'; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

  # Run manifest tests only if there were changes in the cluster chart
  test:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.changes == 'true'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Run tests
      run: |
        make test
